### ISSUE TITLE
consecutive search without search key

### ISSUE THREAD

**Issue by AmirTadmor** [tigrawap/slit#12]
searching with / or ? without specifying a search key should look for the last key that was searched, same way less does

**Comment by tigrawap** [comment]
It's very weird behaviour of less, to disable search you have to / -ESC - enter. Without any indication what happens. 
I don't really want to follow this behaviour. / -> Enter to disable search makes more sense to me  
Unless I miss something.

You can make repeat searches with n or N, exactly as less does. Much more convenient to repeat searches, then to press / -> enter
