### ISSUE TITLE
build.sh 

### ISSUE THREAD

**Issue by Keith-S-Thompson** [tigrawap/slit#5]
The `build.sh` script appears to be for MacOS only, and there are no other build instructions.
My guess is that building it on Linux would be straightforward, but I'm not familiar with Go build systems.

**Comment by tigrawap** [comment]
build.sh is just for me to build releases, which I eventually will improve to build && tag && upload to github

In go you don't need any build tools, you just need go installed and then `go get github.com/tigrawap/slit`
It will download, compile and install

**Comment by tigrawap** [comment]
Also you can download pre-built binary from releases page
