### ISSUE TITLE
Can't change search mode

### ISSUE THREAD

**Issue by notramo** [tigrawap/slit#55]
`Ctrl` + `/` don't work for me.
I don't know if it matters, but I use Hungarian keyboard layout. In this layout, the `/` key can be written by `Shift` + `6`, so if I want to change the search mode, I have to press `Ctrl` + `Shift` + `6`, but it don't work.
### edit:
While reading the source code I noticed that `Ctrl` + `/` only works when the search bar is active. Could it work when the search bar is not active?

**Comment by tigrawap** [comment]
I guess so, although not clear to me why would you change it before searching, i.e, this will require some indication that change was actually made...

**Comment by notramo** [comment]
I have then realized that this wouldn't be too much useful. I think it don't worth the effort it would need, so I close this issue.
