### ISSUE TITLE
colors in follow mode

### ISSUE THREAD

**Issue by xse** [tigrawap/slit#89]
Hello, i'm wondering if `-f` is supposed to use colors.
I installed slit to be able to have my logs without line wrap and still be able to check the cut part if needed.
It's working fine but does not use the colors i get without it.
`Slit Version:  1.3.0` 

Here's an example, on top is `journalctl -f`, on the bottom is `journalctl -f | slit -f`
![2021-07-03 21_21_24-Window](https://user-images.githubusercontent.com/183953/124364879-b192b200-dc44-11eb-8d65-7b49e4aad632.png)

This is happening inside tmux, i tried a couple different terminals with the same results. 
Have a good day!

**Comment by tigrawap** [comment]
try:
SYSTEMD_COLORS=true journalctl | slit
